### ISSUE TITLE
IE 11 Issue

### ISSUE THREAD

**Issue by dbro1** [ejbenke/SPFx-React-Accordion-Section#1]
Hey ejbenke,

I was having an issue getting this to work in our environment using IE11. I discovered that adding a few "references" fixes it.   I added the following imports which seems to have resolved it:

import "core-js/es6/array";
import "es6-map/implement";
import "core-js/modules/es6.array.find";

Cheers!

**Comment by ejbenke** [comment]
Implemented these additions to the web part entry file as suggested by dbro1.  By including these polyfills the web part is now supported in IE11.  Many thanks, dbro1!  Great catch and solution.
