### ISSUE TITLE
List Field Type

### ISSUE THREAD

**Issue by johanvandy** [ejbenke/SPFx-React-Accordion-Section#2]
First off- thanks for makig this available!

What should the field type for 'Content' Be. I have tried Text field ('Rich text' and also 'Enhanced rich text'

When using 'Rich text' line breaks are not rendered for the client.
When using 'Enhanced rich text', the html is not rendered but displayed as part of the content.

I am using the code as provided and made no changes. Any guidance will be appreciated.

![2020-07-03_14-01-27](https://user-images.githubusercontent.com/44995057/86467530-d30d4500-bd35-11ea-85e8-f2b5f6df35f4.jpg)

**Comment by ejbenke** [comment]
Hi Johan - Thanks for your interest in this web part and feedback!

The web part currently only supports Plain Text within the Content text column.  And the lack of line breaks are a limitation.  So, right now it's best suited for simple FAQs with a paragraph or less of text in the Content fields.

I'll update the Readme to reflect that & I'll see what I can do in terms of enhancements to make it more flexible on how the text is displayed.

**Comment by johanvandy** [comment]
Thank you so much. Looking forward to the enhancement. Please keep me posted!

**Comment by ejbenke** [comment]
Hi @johanvandy - I'm happy to report that this enhancement has been completed and added to the project.   The Content panels now support Rich Text.  If you have and older version (1.2 or earlier) deployed in your tenant, update it to the new version (1.3) within your App Catalog. 

Thanks again for the suggestion and getting in touch!

**Comment by johanvandy** [comment]
Awesome @ejbenke
Your efforts and quick response is much appreciated.

Any chance of having it display _Enhanced rich text (Rich text with pictures, tables, and hyperlinks)_?

**Comment by ejbenke** [comment]
Hi @johanvandy - It does also support Enhanced rich text too (images, hyperlinks, etc) now.  You can toggle that option on in your column setting for the Content column and everything you can add there should be rendered properly.  I'll also call that out in the Readme to make it more clear that enhanced rich text is supported too.
