### ISSUE TITLE
Collapsible/Expandable Webpart Title

### ISSUE THREAD

**Issue by gingw** [ejbenke/SPFx-React-Accordion-Section#6]
Hello,

Thank you for creating this code. It helps a lot with newbies like me just learning how to code. My questions is how to make the Accordion SharePoint Webpart Title be collapsible/expandable (I believe this might be called a Nested Accordion), so that all the sections under the Title are collapsed when the user lands on the SharePoint page?

Any guidance would be greatly appreciate.

**Comment by ejbenke** [comment]
Hi @gingw - thanks & glad to hear my project has been helpful.

If you are wanting to modify the project to do a nested accordion, it would definitely add complexity to how the user would have to create the selected SharePoint List to indicate the nesting relationship and then how to implement the actual nesting within the code.  

But to make sure I understand what you're asking, were you hoping to do something that's like the accordion on [this site](https://marniewoodmeade.co.uk/authenticlearning/) where you'd have collapsible sections within other collapsible sections?

**Comment by gingw** [comment]
> Hi @gingw - thanks & glad to hear my project has been helpful.
> 
> If you are wanting to modify the project to do a nested accordion, it would definitely add complexity to how the user would have to create the selected SharePoint List to indicate the nesting relationship and then how to implement the actual nesting within the code.
> 
> But to make sure I understand what you're asking, were you hoping to do something that's like the accordion on [this site](https://marniewoodmeade.co.uk/authenticlearning/) where you'd have collapsible sections within other collapsible sections?

Thank you @ejbenke for taking the time to reply. The site you mention is what I was looking for, but it would be only one level of a Nested Accordion. Here is a specific site example that I was looking for: https://www.coothead.co.uk/css-accordian/index.html. 

The first level of the Nested Accordion would only need to display text and the second level is where the SharePoint List accordion is needed.

**Comment by ejbenke** [comment]
Thanks for the clarification @gingw.  I really like this idea as a variant of this project; here’s how you can do something like that.  

The idea is basically that the outer accordion could have just one collapsible section (e.g. a single `AccordionItem`) with the Title value from the Web Part Property Pane as it’s heading (`AccordionItemHeading`) and then the content within the collapsible panel of that `AccordionItem` (e.g. `AccordionItemPanel`) would contain the entire inner accordion whose content is populated based on your SharePoint List just like in the original version.

To make this modification, in the _\src\webparts\reactAccordion\components\ReactAccordion.tsx_ file replace this `<div>`:

```
        <div>
          <h2>{this.props.accordionTitle}</h2>
          <Accordion allowZeroExpanded> 
            {this.state.items.map((item:any) => {
              return (
                <AccordionItem>
                  <AccordionItemHeading>
                    <AccordionItemButton>
                      {item.Title}
                    </AccordionItemButton>
                  </AccordionItemHeading>
                    <AccordionItemPanel>
                      <p  dangerouslySetInnerHTML={{__html: item.Content}} />
                    </AccordionItemPanel>
                </AccordionItem>
                );
              })
            }
          </Accordion>
        </div> 
```

With this version:
```
     <div>
          <Accordion allowZeroExpanded>
            <AccordionItem>
              <AccordionItemHeading>
                <AccordionItemButton>
                  {this.props.accordionTitle}
                </AccordionItemButton>
              </AccordionItemHeading>
              <AccordionItemPanel>
                  <Accordion allowZeroExpanded>
                    {this.state.items.map((item:any) => {
                      return (
                        <AccordionItem>
                          <AccordionItemHeading>
                            <AccordionItemButton>
                              {item.Title}
                            </AccordionItemButton>
                          </AccordionItemHeading>
                          <AccordionItemPanel>
                            <p  dangerouslySetInnerHTML={{__html: item.Content}} />
                          </AccordionItemPanel>
                        </AccordionItem>
                        );
                      })
                    }
                  </Accordion>
              </AccordionItemPanel>
            </AccordionItem>
          </Accordion>
        </div> 
```

The result will look something like this:
![AccordionNestedExample](https://user-images.githubusercontent.com/5017358/101403483-2b6ae480-388a-11eb-99b3-1966a9b4fe46.png)

As compared to the original version:
![AccordionOriginalExample](https://user-images.githubusercontent.com/5017358/101403512-36257980-388a-11eb-8ffe-d654db54136e.png)

Is that similar to what you had in mind?

**Comment by gingw** [comment]
Thank you @ejbenke and really appreciate you for taking the time to create and explain the code. This is exactly what I had in mind. It makes the SharePoint page cleaner and easier to navigate for the user.

I spent over a week trying to understand and figure out the various codes online to get it to work but was unsuccessful. This is perfect.   

Thank you again.

**Comment by ejbenke** [comment]
You're very welcome @gingw.  And I think how to make this type of modification will be useful to others as well, so glad you asked about it.  

Thanks again for your interest in the project!
